name: Publish to PyPI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'cases/**'
      - 'runtime/**'
      - 'requirements.txt'
      - 'setup.py'

permissions:
  contents: read
  id-token: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.check.outputs.should_publish }}
      version: ${{ steps.check.outputs.version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check if new version
      id: check
      run: |
        # Get the latest commit message
        COMMIT_MSG=$(git log -1 --pretty=%B)
        
        # Check if commit message matches version pattern (e.g., "1A - message")
        if [[ $COMMIT_MSG =~ ^([0-9]+)([A-Z])\ -\ .+ ]]; then
          MAJOR="${BASH_REMATCH[1]}"
          MINOR_LETTER="${BASH_REMATCH[2]}"
          
          # Convert letter to number (A=0, B=1, C=2, etc.)
          MINOR=$(($(printf '%d' "'${MINOR_LETTER}") - 65))
          
          # Create semantic version
          VERSION="${MAJOR}.${MINOR}.0"
          
          echo "should_publish=true" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "✅ New version detected: $VERSION (from commit: $COMMIT_MSG)"
        else
          echo "should_publish=false" >> $GITHUB_OUTPUT
          echo "version=0.0.0" >> $GITHUB_OUTPUT
          echo "ℹ️  No version tag in commit message. Skipping publish."
          echo "   Expected format: '<MAJOR><LETTER> - <message>' (e.g., '1A - Initial release')"
        fi

  test:
    needs: check-version
    if: needs.check-version.outputs.should_publish == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build C runtime
      run: |
        cd runtime
        make
    
    - name: Run tests
      run: |
        cd src
        python tests.py

  publish:
    needs: [check-version, test]
    if: needs.check-version.outputs.should_publish == 'true'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/frscript
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      env:
        PACKAGE_VERSION: ${{ needs.check-version.outputs.version }}
      run: |
        echo "Building version $PACKAGE_VERSION"
        python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        verbose: true
